### PR TITLE
add base vue api provider context component

### LINKED ISSUE #8: 005-Implement Base Provider Component for API injection
# Task Summary

Implement the polkadot api provider component that allows dependency injection, hooks, and provider context to be accessed from other components using the Composition API.

## Subtasks

This ticket will be considered as finished when the following items are fulfilled:

- [ ] setup a basic asynchronous provider parent component
- [ ] create a basic state management logic and event hooks that are accessible from other components within the context
- [ ] add loading screen + error handling
- [ ] implement basic polkadot API hook
- [ ] simple display of Substrate account node balance

## Dependencies

https://github.com/PlasmNetwork/plasm-apps-vue/issues/2

## Difficulty

6/10

## Estimated Implementation Time

> Note: the task start date is considered to be the day the ticket was opened or the next day when the dependent task was closed

- **Optimistic**: 5 days
- **Normal**: 10 days
- **Pessimistic**: 2 weeks

### PR DESCRIPTION
**Pull request by hoonsubin**
# Pull Request Summary

this pull request will add the basic framework for using the context provider component to inject dependencies to the chain components.

## Check List

- [x] contains breaking changes
  - [x] adds new feature
  - [x] modifies existing feature
- [x] other task relies on this pull request
- [ ] non-coding changes

## Change Log

This pull request makes the following changes:

### Adds

- basic polkadot provider component

### Fixes

- async error handling method

### Changes

- overall project folder structure
- project serving script command

## To-dos

[list future tasks and other to-dos that should be finished for this pull request to be able to merge, or things that you will do after you merge it]

- [x] add check to see if the UI is connected to a node
- [x] add a basic placeholder loading screen
- [x] finalize the `PolkadotProvider` component by adding the API initialization handler

### CODE REVIEW

**Review by satellitex — COMMENTED** [review]
I think it would be better to split the `provider` and `component` directories. Because `component` is view's but `provider` is not.

**Comment by hoonsubin** [comment]
@satellitex okay. In that case, I'll work on a better directory structure to make it more intuitive

**Review by satellitex — APPROVED** [review]

**Review by taskooh — APPROVED** [review]
Looks good! In this case, in order to create another hook, we should add new variable to polkadotContext, right?

**Comment by hoonsubin** [comment]
@taskooh Yes, it's much cleaner to keep all hooks and objects directly relying on the polkadot-api in the same provider component. For some unrelated objects (like web3js or MetaMask hooks), we might need to create a new provider component.
To be precise, you can add an object member here https://github.com/PlasmNetwork/plasm-apps-vue/pull/9/files#diff-7ff6e50b9fc11fcd1659f916f6a6dd3f295627c8eb112470006a64fb8683f15fR14 and initialize it from the provider component.

**Pull request merged**
